### ISSUE TITLE
1-Wire Bus support

### ISSUE THREAD

**Issue by zokl** [the78mole/esphome_components#2]
Hi @the78mole.  I would like to use your board but i need to make small modiffication. I would like to add there 1-wire iface for sensors to the boiler and end it by terminals: https://de.farnell.com/phoenix-contact/pt-1-5-8-pvh-5-0/terminal-block-pluggable-8pos/dp/1793552?gclid=Cj0KCQjw3eeXBhD7ARIsAHjssr_5iBLzo18RP7qZRayOeb2QF7z_NSONAUBIKK1RHS0NTV0xu_wFagAaAnYJEALw_wcB&mckv=_dc%7Cpcrid%7C%7Cplid%7C%7Ckword%7C%7Cmatch%7C%7Cslid%7C%7Cproduct%7C1793552%7Cpgrid%7C%7Cptaid%7C%7C&CMP=KNC-GCZ-GEN-SHOPPING-PMax&gross_price=true

Do you plan to implement 1-Wire and terminals for I2C bus?

In your last desing 0.0.4 you fix the issue with power and module works without restarts?

**Comment by the78mole** [comment]
Hi zokl,

in my Installation, it worked always without restarts, but a few people reportet problems. With the larger capacitors, the problem seems to be vanished completely, but I can not guarantee it.

You could use the P3, P4 and P7 to P12 signals. They are easily accessible on the jumper row and the only modifications you need to do are about the components used for filtering and damping the analog signals:
![image](https://user-images.githubusercontent.com/7723396/184629232-7e7c8aa9-d312-4ab1-8828-7f530d23f1cd.png)

Should be an easy task to add the interfacing for onewire (pull-up + optional low-pass).

Regards,
Daniel

**Comment by the78mole** [comment]
Here you could find some information about the best interfacing practices for 1-wire:
https://www.maximintegrated.com/en/design/technical-documents/tutorials/1/148.html

Especially the "Appendix A. Improved CPU Bus Interface" and Appendix B:
![image](https://user-images.githubusercontent.com/7723396/184629844-b682851a-c92c-45a9-bc75-cdd625d6ff9a.png)

**Comment by zokl** [comment]
I am considering redoing the board and using terminal strips instead of PLS strips. They will be easier to handle the wires. Just making sure I wouldn't do any unnecessary work if you already have some of this planned.

**Comment by the78mole** [comment]
Du you need the latest KiCad-Project?

**Comment by zokl** [comment]
> Du you need the latest KiCad-Project?

If you push it to github, I made or a pull request.

**Comment by the78mole** [comment]
The HW ist hosted on Gitlab...
https://gitlab.com/the78mole/buderus-km271-mm

**Comment by zokl** [comment]
> The HW ist hosted on Gitlab...
> https://gitlab.com/the78mole/buderus-km271-mm

Yes I know, i forked latest version 0.0.4.

**Comment by the78mole** [comment]
I just merges the MM-One (the one above, a modified version from a friend) and my repo to have the same HW state...
https://gitlab.com/the78mole/logamatic_2107_wifi_comm
